version: "3.8"

services:
  postgres:
    image: postgres:17.4
    container_name: treasure_box_DB
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"
    networks:
      - treasure_box_network

volumes:
  pgdata:
    driver: local

networks:
  treasure_box_network:
    driver: bridge
